image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python -V
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install -U -r requirements.txt
stages:
  - Quality
  - Test
  - Build
  - Deploy
  - Examples
  - Documentation
  - Pages

pylint:
  stage: Quality
  script:
    - pip install -U pylint-gitlab
    - pylint hausse --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter . > codeclimate.json
  artifacts:
    reports:
      codequality: codeclimate.json
    when: always

pytest:
  stage: Test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

build:
  stage: Build
  script:
    - pip install -U build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

portfolio:
  stage: Examples
  script:
    - python -m hausse examples/portfolio/hausse.json
  artifacts:
    paths:
      - examples/portfolio/
notes-extraction:
  stage: Examples
  script:
    - python -m hausse examples/notes-extraction/hausse.json

reference:
  stage: Documentation
  script:
    - pip install -U Sphinx
    - sphinx-apidoc -o docs/src/ref hausse
  artifacts:
    paths:
      - docs/src/ref/*
docs:
  stage: Pages
  script:
    - pip install -U Sphinx sphinx-rtd-theme
    - sphinx-build -b html docs/src public