image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python -V  # Print out python version for debugging
  - virtualenv .venv
  - source .venv/bin/activate
test:
  script:
    - pip install pytest pybars3 markdown2 pyyaml
    - python -m pytest
build:
  script:
    - pip install pytest pybars3 markdown2 pyyaml
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
