image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python -V  # Print out python version for debugging
  - virtualenv .venv
  - source .venv/bin/activate
test:
  script:
    - pip install -U pytest pybars3 markdown2 pyyaml
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
build:
  script:
    - pip install -U build pybars3 markdown2 pyyaml
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
docs:
  script:
    - pip install -U Sphinx sphinx-rtd-theme
    - sphinx-build -b html docs/src public