image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python -V
  - virtualenv .venv
  - source .venv/bin/activate
  - python -m pip install --upgrade
  - pip install -U -r requirements.txt
stages:
  - Quality
  - Test
  - Build
  - Blueprints
  - Deploy
  - Documentation
  - Pages

include:
  - .gitlab/pipelines/pylint.gitlab-ci.yml
  - .gitlab/pipelines/pytest.gitlab-ci.yml
  - .gitlab/pipelines/build.gitlab-ci.yml
  - .gitlab/pipelines/blueprints.gitlab-ci.yml
  - .gitlab/pipelines/reference.gitlab-ci.yml
  - .gitlab/pipelines/docs.gitlab-ci.yml
