image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python -V
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install -U -r requirements.txt
stages:
  - Static Analysis
  - Test
  - Build
  - Deploy
  - Examples
  - Documentation

flake8:
  stage: Static Analysis
  script:
    - pip install -U flake8
    - flake8 --max-line-length=120 hausse
pylint:
  stage: Static Analysis
  script:
    - pip install -U pylint
    - pylint -d C0301 hausse

pytest:
  stage: Test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

build:
  stage: Build
  script:
    - pip install -U build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

portfolio:
  stage: Examples
  script:
    - python -m hausse examples/portfolio/hausse.json
notes-extraction:
  stage: Examples
  script:
    - python -m hausse examples/notes-extraction/hausse.json

docs:
  stage: Documentation
  script:
    - pip install -U Sphinx sphinx-rtd-theme
    - sphinx-build -b html docs/src public